### ISSUE TITLE
Tool Addition Request

### ISSUE THREAD

**Issue by xJayson** [MoonWalker440/TeleBotList#1]
Can you add this downloading tool under Go?

https://github.com/iyear/tdl

Thanks.

**Comment by MoonWalker440** [comment]
I Don't think that there's any direct connection with bots so can't add this tool. I also need to remove some links from my list such as Teledrive, Watg bridge etc. Because now I understand that there's no connection with bots in these tools.

**Comment by xJayson** [comment]
Could include both bots and telegram related repos, I don't see a problem with thay

**Comment by MoonWalker440** [comment]
Hmm you are right. I should make a separate section for this too. Okay I will add the 'tdl' tool
