### ISSUE TITLE
Suggestion

### ISSUE THREAD

**Issue by Hinoserm** [MoonWalker440/TeleBotList#3]
Looks like you could use some more C# examples --

@makefoxbot
https://github.com/Hinoserm/makefoxbot
AI image tools focused on providing a fast user experience, written to speak MTProto directly to bypass the slow bot API.

Not really intended to be deployed publically, but might be useful as an example of working directly with MTProto in C#.

**Comment by MoonWalker440** [comment]
But this is just an example repo. I can't add it. I can only add either bot or tool. Hope you understand
